### ISSUE TITLE
only works with no movement

### ISSUE THREAD

**Issue by jhlothamer** [Maujoe/godot-simple-wind-shader-2d#1]
This works great for a static scene, but add a camera and moving character and the movement is massively sped up.  Is there any work around for that?  Or would anyone have any tips on how to fix that with this shader?

To reproduce the issue, open the demo app and move the grass sprite around in the scene by clicking and then dragging.

**Comment by Maujoe** [comment]
Oh yes I see, I also noticed that the wind strength differ with the view size.
I have created a new shader version that is view independent. 

Unfortunately all sprites have the same wind motion (no variation), that's a limitation for now. I will look for a solution. But I hope it helps you currently.
